(function () {
"use strict";
var nav = document.getElementById("nav");
var navToggle = document.getElementById("navToggle");
var navLinks = document.getElementById("navLinks");
window.addEventListener("scroll", function () { if (window.scrollY > 60) { nav.classList.add("scrolled"); } else { nav.classList.remove("scrolled"); } }, { passive: true });
navToggle.addEventListener("click", function () { navLinks.classList.toggle("open"); navToggle.setAttribute("aria-expanded", navLinks.classList.contains("open")); });
navLinks.querySelectorAll("a").forEach(function (link) { link.addEventListener("click", function () { navLinks.classList.remove("open"); }); });
var storyField = document.getElementById("c-story");
var charCount = document.getElementById("charCount");
if (storyField && charCount) { storyField.addEventListener("input", function () { var words = storyField.value.trim() === "" ? [] : storyField.value.trim().split(/\s+/); var count = words.length; charCount.textContent = count + " word" + (count !== 1 ? "s" : "") + (count < 100 ? " (100 minimum)" : " OK"); charCount.style.color = count >= 100 ? "#065f46" : ""; }); }
function isBot(form) { var h = form.querySelector("[name=website],[name=url]"); return h && h.value.length > 0; }
var lastSubmit = {};
function rateLimited(id) { var now = Date.now(); if (lastSubmit[id] && (now - lastSubmit[id]) < 60000) { return true; } lastSubmit[id] = now; return false; }
function showMsg(el, type, text) { el.className = "form-msg " + type; el.textContent = text; el.style.display = "block"; el.scrollIntoView({ behavior: "smooth", block: "nearest" }); }
function buildMailto(to, subject, bodyText) { return "mailto:" + to + "?subject=" + encodeURIComponent(subject) + "&body=" + encodeURIComponent(bodyText); }
var contactForm = document.getElementById("contactForm");
var contactMsg = document.getElementById("contactMsg");
var contactSubmit = document.getElementById("contactSubmit");
if (contactForm) { contactForm.addEventListener("submit", function (e) { e.preventDefault(); if (isBot(contactForm)) { return; } if (rateLimited("contact")) { showMsg(contactMsg, "error", "Please wait before submitting again."); return; } var nm = contactForm.querySelector("[name=name]").value.trim(); var em = contactForm.querySelector("[name=email]").value.trim(); var sb = contactForm.querySelector("[name=subject]").value; var ms = contactForm.querySelector("[name=message]").value.trim(); var og = contactForm.querySelector("[name=organization]").value.trim(); if (!nm || !em || !sb || !ms) { showMsg(contactMsg, "error", "Please fill in all required fields."); return; } if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(em)) { showMsg(contactMsg, "error", "Please enter a valid email address."); return; } contactSubmit.disabled = true; contactSubmit.textContent = "Sending..."; var bd = "Name: " + nm + "\n" + (og ? "Org: " + og + "\n" : "") + "Email: " + em + "\n" + "Subject: " + sb + "\n\n" + ms; window.location.href = buildMailto("info@mercury-rx.com", "[MPC] " + sb, bd); setTimeout(function () { showMsg(contactMsg, "success", "Your message is ready in your email client. Please click Send to complete your inquiry."); contactForm.reset(); contactSubmit.disabled = false; contactSubmit.textContent = "Send Message"; }, 800); }); }
var careersForm = document.getElementById("careersForm");
var careersMsg = document.getElementById("careersMsg");
var careersSubmit = document.getElementById("careersSubmit");
if (careersForm) { careersForm.addEventListener("submit", function (e) { e.preventDefault(); if (isBot(careersForm)) { return; } if (rateLimited("careers")) { showMsg(careersMsg, "error", "Please wait before submitting again."); return; } var nm = careersForm.querySelector("[name=name]").value.trim(); var em = careersForm.querySelector("[name=email]").value.trim(); var rl = careersForm.querySelector("[name=role]").value; var st = careersForm.querySelector("[name=story]").value.trim(); var lc = careersForm.querySelector("[name=location]").value; var li = careersForm.querySelector("[name=license]").value.trim(); if (!nm || !em || !rl || !st) { showMsg(careersMsg, "error", "Please fill in all required fields."); return; } if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(em)) { showMsg(careersMsg, "error", "Please enter a valid email address."); return; } var wc = st === "" ? 0 : st.split(/\s+/).length; if (wc < 100) { showMsg(careersMsg, "error", "Your story needs at least 100 words. Tell us more."); return; } careersSubmit.disabled = true; careersSubmit.textContent = "Submitting..."; var bd = "Name: " + nm + "\nEmail: " + em + "\nRole: " + rl + "\n" + (lc ? "Location: " + lc + "\n" : "") + (li ? "License: " + li + "\n" : "") + "\n--- Story ---\n" + st; window.location.href = buildMailto("info@mercury-rx.com", "[MPC Careers] " + rl + " — " + nm, bd); setTimeout(function () { showMsg(careersMsg, "success", "Your application is ready in your email client. Please click Send. We read every story."); careersForm.reset(); if (charCount) { charCount.textContent = "0 words"; } careersSubmit.disabled = false; careersSubmit.textContent = "Submit My Application"; }, 800); }); }
if ("IntersectionObserver" in window) { var st2 = document.createElement("style"); st2.textContent = ".fade-in{opacity:0;transform:translateY(24px);transition:opacity 0.7s ease,transform 0.7s ease}.fade-in.visible{opacity:1;transform:none}"; document.head.appendChild(st2); var els = document.querySelectorAll(".pharmacy-card,.pillar,.stat,.about-quote,.community-list li,.about-text-col p"); els.forEach(function(el){el.classList.add("fade-in");}); var obs = new IntersectionObserver(function(entries){entries.forEach(function(en){if(en.isIntersecting){en.target.classList.add("visible");obs.unobserve(en.target);}});},{threshold:0.12}); els.forEach(function(el){obs.observe(el);}); }
})();